### ISSUE TITLE
Forcast.io current conditions issue

### ISSUE THREAD

**Issue by elgigantor** [tipichris/bbcwx#12] opened 2015-02-17 15:52 UTC
Hey.  this is my issue  usually when it snows lightly here forcast.io shows snow on the webpage but in your app it always says foggy.  i've tried what you suggested by restarting the app but it didnt help.  the forcast and current temps are perfect but it's just the current conditions with image.  i know you mentioned it may be a sync issue but i had this issue for a week straight.  right now it works great but who know how long it will.  dont get me wrong, i love your work and you did a great job with this desklet.  i'm just a bit finicky,  thanks dude

**Comment by tipichris** [comment] 2015-02-17 21:24
I can't see an obvious problem with the mapping of snow and fog. Are both the icon and the text wrong? 

What lon and lat are you using? I'll set up an instance with same settings. If you then update this issue next time the problem occurs I can try and track it down. If I'm awake - time difference might be an issue:)

**Comment by elgigantor** [comment] 2015-02-17 22:59
yes both icon and text are wrong. site says light snow and on the desklet it shows fog in image and text.  only happens sometimes though.  the longest it lasted was over a week.... the long and lat is 45.4667,-75.5167

**Comment by tipichris** [comment] 2015-02-18 08:14
Icon and text come from a different part of the data feed, and text is reproduced directly, not interpreted in anyway. If they are both wrong it suggests the problem lies in forecast.io's feed. Next time you notice this problem check out https://api.forecast.io/forecast/YOUR_API_KEY/45.4667,-75.5167?units=ca, replacing YOUR_API_KEY obviously. Then send me the first few lines.

**Comment by elgigantor** [comment] 2015-02-18 16:31
will do.  thanks for your help

**Comment by tipichris** [comment] 2015-02-21 23:48
OK, I've just seen this happen. Desklet says foggy, website says snow. And here's the raw data from the API:

`"currently":{"time":1424562098,"summary":"Foggy","icon":"fog","nearestStormDistance":16,"nearestStormBearing":160,"precipIntensity":0,"precipProbability":0,"temperature":-10.69,"apparentTemperature":-13.67,"dewPoint":-12.22,"humidity":0.88,"windSpeed":4.96,"windBearing":68,"visibility":1.24,"cloudCover":1,"pressure":1018.11,"ozone":401.07}`

So it looks like the fault lies with forecast.io, the Desklet is accurately displaying the data it gets from them. Perhaps raise it with them? 

As it's outside my control I'll close this issue.

**Closed by tipichris** 2015-02-21 23:48 UTC
