### ISSUE TITLE
no actual weather data ????

### ISSUE THREAD

**Issue by quickgreyfox** [tipichris/bbcwx#31] opened 2018-03-30 12:12 UTC
The desklet didn't show weather information anymore. The data retrieval path seems to be broken!

**Comment by tipichris** [comment] 2018-03-30 12:35
See issue #30. If you are using the  BBC data source this is probably the same issue. The BBC are migrating to a new platform and the amount of information on the old has been reducing over the last few days.

A patch is ready and will be rolled out in the next few days. However, the BBC's new platform currently lacks a lot of information on current weather. 

Closing as duplicate of #30.

**Closed as completed by tipichris** 2018-03-30 12:35 UTC

**Comment by quickgreyfox** [comment] 2018-04-01 09:18
Chris, thanks for your advice and quick response!
